config/routes.rb
Rails.application.routes.draw do
  resource :session, except: [ :destroy ]
  resources :passwords, param: :token
  resources :courses, only: [ :create ] do
    member do
      post :create_telegram_group
    end
  end

  get "sign_out" => "sessions#destroy", as: :sign_out
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :teacher, -> { faculty }, class_name: "User"
  belongs_to :teacher_assistant, -> { faculty }, class_name: "User", optional: true
  has_many :course_students
  has_many :students, -> { student }, through: :course_students

  def self.list_for(user)
    case user.role.to_sym
    when :administration
      all
    when :student
      includes(:students).where(course_students: { student_id: user.id })
    when :faculty
      where(teacher_id: user.id).or(where(teacher_assistant_id: user.id))
    else
      []
    end
  end
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student, -> { student }, class_name: "User"
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  enum :role, { administration: 1, faculty: 2, student: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
    helper_method :authenticated_user
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      Current.session.present?
    end

    def authenticated_user
      return unless authenticated?

      Current.session.user
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session = find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_url
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def create
    @course = Course.new(course_params)

    alert = @course.save ? "created" : "failed"

    redirect_to root_path, alert: alert
  end

  def create_telegram_group
    @course = Course.find(params[:id])
    create_group = CourseService::CreateTelegramGroup.new(@course)

    alert = create_group.call ? "created" : "failed"

    redirect_to root_path, alert: alert
  end

  private

  def course_params
    params.require(:course).permit(:subject, :teacher_id, :teacher_assistant_id, student_ids: [])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @courses = Course.list_for(authenticated_user)

    if authenticated_user.administration?
      @new_course = Course.new
      @teachers = User.faculty
      @students = User.student
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_url, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_url, notice: "Password has been reset."
    else
      redirect_to edit_password_url(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_url, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_url, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
  def course_telegram_group_link(course)
    if course.telegram_group_link.present?
      link_to "join telegram group", course.telegram_group_link, target: "_blank"
    elsif authenticated_user.administration?
      button_to "create telegram group", create_telegram_group_course_path(course)
    end
  end
end

app/views/application/_header.html.erb
<div class="spec-header">
  <h1><%= content_for(:title) %></h1>

  <% if authenticated? %>
    <%= authenticated_user.email_address %>
    <%= authenticated_user.role %>
    <%= link_to 'Sign out', sign_out_path %>
  <% end %>
</div>

<%= tag.div(flash[:alert]) if flash[:alert] %>

app/views/courses/_form.html.erb
<%= simple_form_for @new_course do |f| %>
  <%= f.input :subject %>
  <%= f.association :teacher, label_method: :email_address, include_blank: false %>
  <%= f.association :teacher_assistant, label_method: :email_address %>
  <%= f.association :students, label_method: :email_address, as: :check_boxes %>
  <%= f.button :submit %>
<% end %>

app/views/courses/_list.html.erb
<ul>
  <% @courses.each do |course| %>
    <li>
      <%= course.subject %>
      <%= course.teacher.email_address %>
      <%= course.students.count %>
      <%= course_telegram_group_link(course) %>
    </li>
  <% end %>
</ul>

app/views/dashboard/_administration.html.erb
<% content_for(:title) { 'Administration Dashboard' } %>

<h2>Courses</h2>
<%= render 'courses/list' %>

<h2>Create new course</h2>
<%= render 'courses/form' %>

app/views/dashboard/_faculty.html.erb
<% content_for(:title) { 'Faculty Dashboard' } %>

<h2>Courses</h2>
<%= render 'courses/list' %>

app/views/dashboard/_student.html.erb
<% content_for(:title) { 'Student Dashboard' } %>

<h2>Courses</h2>
<%= render 'courses/list' %>

app/views/dashboard/index.html.erb
<%= render authenticated_user.role %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "School Telegram" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/favicon.ico" type="image/ico">
    <link rel="apple-touch-icon" href="/favicon.ico">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'header' %>
    <%= yield %>
  </body>
</html>